name: Build and deploy Python app to Azure Web App - agentic-bank-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create true
          poetry install --no-interaction --no-ansi

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !.venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Fetch Key Vault secrets
        id: keyvault
        run: |
          AZURE_OPENAI_ENDPOINT=$(az keyvault secret show --vault-name "agentic-bank-kv" --name "AZURE_OPENAI_ENDPOINT" --query value -o tsv)
          AZURE_OPENAI_API_KEY=$(az keyvault secret show --vault-name "agentic-bank-kv" --name "AZURE_OPENAI_API_KEY" --query value -o tsv)
          CHAINLIT_JWT_SECRET=$(az keyvault secret show --vault-name "agentic-bank-kv" --name "CHAINLIT_JWT_SECRET" --query value -o tsv)
          echo "AZURE_OPENAI_ENDPOINT=$AZURE_OPENAI_ENDPOINT" >> $GITHUB_ENV
          echo "AZURE_OPENAI_API_KEY=$AZURE_OPENAI_API_KEY" >> $GITHUB_ENV
          echo "CHAINLIT_JWT_SECRET=$CHAINLIT_JWT_SECRET" >> $GITHUB_ENV

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'agentic-bank-web'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4996D8F13EAF47D1A78A890586AECBE3 }}

      - name: Set Web App environment variables from Key Vault
        run: |
          az webapp config appsettings set \
            --name agentic-bank-web \
            --resource-group agentic-bank-rg \
            --settings AZURE_OPENAI_ENDPOINT=$AZURE_OPENAI_ENDPOINT \
                       AZURE_OPENAI_API_KEY=$AZURE_OPENAI_API_KEY \
                       CHAINLIT_JWT_SECRET=$CHAINLIT_JWT_SECRET
